package.json, yarn.lock
- Moved component to javascript-components
=> BACKLOG-10540 Externalize LanguageSwitcher component

package.json, src/javascript/main.js, yarn.lock
https://jira.jahia.org/browse/BACKLOG-11820
Replaced @jahia/registry by @jahia/ui-extender , updated libs
=> BACKLOG-11820 : Replaced registry

package.json, yarn.lock
=> BACKLOG-12225: Bump moonstone version to 0.6.0

.gitignore, package.json, src/javascript/main.js, yarn.lock
=> BACKLOG-12157 : Added react-redux in libs

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-12235
update moonstone, which fix some display issues
=> BACKLOG-12235 update moonstone, which fix some display issues

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-12339
update moonstone
=> BACKLOG-12339 update moonstone

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-12429
=> BACKLOG-12429 : update @jahia/icons

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-12475
=> BACKLOG-12475 : udpate @jahia/ui-extender

package.json, yarn.lock
=> MOON-51: update @jahia/moonstone

package.json, yarn.lock
=> BACKLOG-12500: Bump to @jahia/moonstone@0.11.0

package.json, yarn.lock
=> BACKLOG-12517: Bump to @jahia/moonstone@0.11.1

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-12393
=> BACKLOG-12393 : update data-helper

pom.xml, src/javascript/init.js, src/javascript/main.js, src/main/java/org/jahia/modules/dxwebpack/Main.java, src/main/java/org/jahia/modules/dxwebpack/Resources.java, src/main/resources/javascript/js-load.js, src/main/resources/root.jsp
https://jira.jahia.org/browse/BACKLOG-12161
=> BACKLOG-12161 : Added appshell

src/main/resources/root.jsp
https://jira.jahia.org/browse/BACKLOG-12590
=> BACKLOG-12590 : load jahia JS before anthracite

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-12602
=> BACKLOG-12602 : update @jahia/ui-extender

src/main/java/org/jahia/modules/dxwebpack/Main.java
https://jira.jahia.org/browse/BACKLOG-12501
allow to extend jahia app shell with a simple jahia.json file
=> BACKLOG-12501 allow to extend jahia app shell with a simple jahia.json file

yarn.lock
https://jira.jahia.org/browse/BACKLOG-12615
fix yarn lock
=> BACKLOG-12615 fix yarn lock

src/javascript/main.js
https://jira.jahia.org/browse/BACKLOG-12504
expose moonstone in window.jahia.moonstone
=> BACKLOG-12504 expose moonstone in window.jahia.moonstone

docs/declare-new-module.md
https://jira.jahia.org/browse/BACKLOG-12527
update documentation how to declare a module
=> BACKLOG-12527 update documentation how to declare a module

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-12668
=> BACKLOG-12668 : bump version of @jahia/ui-extender

webpack.config.js, webpack.libraries.config.js
https://jira.jahia.org/browse/BACKLOG-12714
=> BACKLOG-12714: Fix supported browser versions

docs/declare-new-module.md
https://jira.jahia.org/browse/BACKLOG-12697
update documentation with a server settings example
=> BACKLOG-12697 update documentation with a server settings example

webpack.libraries.config.js
=> Fix rxjs parse .map file errors

src/main/java/org/jahia/modules/dxwebpack/Main.java, src/main/resources/root.jsp
=> BACKLOG-12699 : Handle login, use rewrite rules

src/javascript/publicPath.dll.js, webpack.libraries.config.js
https://jira.jahia.org/browse/BACKLOG-12748
=> BACKLOG-12748: fix loading of ressources in dll

package.json, yarn.lock
=> BACKLOG-12764: Bump version of data-helper

package.json, yarn.lock
=> BACKLOG-12761 : Bump ui-extender

package.json, src/javascript/appShell.js, src/javascript/appShell.spec.js, src/javascript/jahia.js, src/javascript/redux/ReduxProvider.jsx, src/javascript/redux/register.jsx, yarn.lock
=> BACKLOG-12157 : Moved redux

package.json, yarn.lock
=> BACKLOG-12789: Bump versions

src/main/java/org/jahia/modules/dxwebpack/Main.java
https://jira.jahia.org/browse/BACKLOG-12664
Just disable caching on servlet
=> BACKLOG-12664 : Disable cache on servlet

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-12798
update moonstone
=> BACKLOG-12798 update moonstone

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-12820
=> BACKLOG-12820: Bump versions of ui-extender

package.json, yarn.lock
=> BACKLOG-12865: Bump version of moonstone

src/main/java/org/jahia/modules/appshell/Main.java
https://jira.jahia.org/browse/BACKLOG-12570
=> BACKLOG-12570 : Allows multiple scripts

src/main/java/org/jahia/modules/appshell/Main.java
https://jira.jahia.org/browse/BACKLOG-12570
Allows to pass scripts not in /modules/xxx , but somewhere else in the context if it starts with /
=> BACKLOG-12570 : Allows absolute path

src/main/java/org/jahia/modules/appshell/Main.java, src/main/resources/root.jsp
https://jira.jahia.org/browse/BACKLOG-12863
=> BACKLOG-12863 : fix login issue

package.json, yarn.lock
https://jira.jahia.org/browse/MOON-113
=> MOON-113: Bump versions

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-12561
=> BACKLOG-12561: Bump versions

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-13021
=> BACKLOG-13021: Bump versions of data-helper

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-12159
=> BACKLOG-12159: Bump version react-material

package.json, yarn.lock
https://jira.jahia.org/browse/MOON-115
=> MOON-115: Bump moonstone version

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-13027
=> BACKLOG-13027 : Bump ui-extender

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-12940
Upgrade moonstone
=> BACKLOG-12940: Upgrading moonstone, its also concern some other tickets

docs/declare-new-module.md
https://jira.jahia.org/browse/BACKLOG-13026
Renamed main route target to have consistent and significant naming. Avoid confusion with nav targets.
=> BACKLOG-13026: renamed route

src/main/resources/root.jsp
https://jira.jahia.org/browse/BACKLOG-13114
=> BACKLOG-13114: Added flag for license validity

src/main/java/org/jahia/modules/appshell/Main.java
https://jira.jahia.org/browse/BACKLOG-13064
=> BACKLOG-13064: get first site found if there's no default site

src/main/java/org/jahia/modules/appshell/Main.java, src/main/resources/root.jsp
https://jira.jahia.org/browse/BACKLOG-13191
=> BACKLOG-13191 : Set site default langauge

LICENSE.txt, README.md, pom.xml, src/main/java/org/jahia/modules/appshell/Main.java
Updated copyright year to 2020
=> BACKLOG-13160 - Updated copyright to 2020

package.json, yarn.lock
Updating Moonstone version to 0.15.9.
=> Bump Moonstone version to 0.15.9

src/main/java/org/jahia/modules/appshell/Main.java
https://jira.jahia.org/browse/BACKLOG-13162
=> BACKLOG-13162: Add content-type header

package.json, yarn.lock
Upgrade Moonstone version to 0.15.11.
=> Upgrade Moonstone to 0.15.11

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-13198
=> BACKLOG-13198: Bump moonstone version

README.md, docs/extend-ui.md
My last commit for Jahia :)
It was a pleasure ;)
=> :beers: Add documentation about registry

package.json, yarn.lock
https://jira.jahia.org/browse/QA-12920
=> QA-12920 : bump data-helper version

src/main/resources/root.jsp
Escape javascript string to avoid special character issue between Java and Javascript
=> QA-13004: Escape javascript string to avoid special character issue 

package.json, yarn.lock
https://jira.jahia.org/browse/QA-13003
=> QA-13003 update design-system-kit dependency

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-14225
=> BACKLOG-14225: Updates @jahia/design-system-kit dependency

src/javascript/jahia.js, src/javascript/jahia.spec.js, webpack.libraries.config.js
https://jira.jahia.org/browse/BACKLOG-14204
* Fixes font loading issue where fonts were not being loaded at the correct URL
* Moonstone font is now being loaded correctly across Jahia application
=> BACKLOG-14204: Changes jahia.js ES6 imports to commonjs imports

.circleci/.circleci.settings.xml, .circleci/config.yml, .github/workflows/triggerCircleCIOnPR.yml
Add a CircleCI configuration (copied from jContent)
=> Add CircleCI configuration

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-14290
* Updated version of @jahia/design-system-kit from 1.1.6 to 1.1.7
=> BACKLOG-14290: Bump @jahia/design-system-kit version

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-14306
=> BACKLOG-14306: Bump ui-extender

src/main/resources/root.jsp
https://jira.jahia.org/browse/BACKLOG-14389
Optimize JSP for EL 3.0
=> BACKLOG-14389: Optimize JSP

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-14310
https://jira.jahia.org/browse/BACKLOG-14311
* Bump Moonstone version to include font bug fixes
=> BACKLOG-14310: Bump moonstone version from 0.16.0 to 0.16.1

src/main/java/org/jahia/modules/appshell/Main.java, src/main/resources/META-INF/urlrewrite-app-shell.xml
https://jira.jahia.org/browse/BACKLOG-14458
please squash and merge the commit when merging keeping (BACKLOG-14458) as reference. 
Thank you!
=> BACKLOG-14458 : add checksum to js main app filenames. 

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-12933
=> BACKLOG-12933: working version of ui-extender

package.json, yarn.lock
=> BACKLOG-12933: Updated version

package.json, yarn.lock
https://jira.jahia.org/browse/QA-13071, QA-13117
=> QA-13071, QA-13117: bump version for data-helper

.eslintignore, .gitignore, pom.xml, src/main/resources/javascript/loader.js, yarn.lock
https://jira.jahia.org/browse/QA-12985
=> QA-12985: Fixed test on IE, added timeout on loader after 15s

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-14270
=> BACKLOG-14270: bump ui-extender

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-14680
=> BACKLOG-14680: bump ui-extender

pom.xml
=> BACKLOG-14377 - Updated scm tag in pom.xml to match branch

package.json, yarn.lock
https://jira.jahia.org/browse/QA-13109
=> QA-13109: Bump ui-extender

package.json, yarn.lock
https://jira.jahia.org/browse/QA-13379
=> QA-13379: bump data-helper

.circleci/config.yml
One one of those commands executed after merge
=> Fixed incorrect config

src/main/java/org/jahia/modules/appshell/Main.java, src/main/resources/root.jsp
https://jira.jahia.org/browse/TECH-284
=> TECH-284 : fix context for remotes

package.json, yarn.lock
https://jira.jahia.org/browse/MOON-223
=> MOON-223: Bump moonstone version to 1.0.0

src/javascript/redux/ReduxProvider.jsx
https://jira.jahia.org/browse/QA-13505
=> QA-13505: Exposes redux store

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-15220
=> BACKLOG-15220: Bump version of design-system-kit

pom.xml, src/main/resources/root.jsp
https://jira.jahia.org/browse/TECH-319
Replace LicenseCheckerService.Stub with LicenseCheckUtils as LicenseCheckerService.Stub is only available when bundle is deployed
=> TECH-319: Adapt code for new license package

.circleci/config.yml, tests/.env.example, tests/docker-compose.yml, tests/package.json, tests/yarn.lock
Since we renamed the snapshot to snapshot-dev (to make room for the non-dev snapshot image), we needed to update the name here.
=> Updated docker snapshot image name

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-15626
=> BACKLOG-15626: Bump ui-extender

src/main/java/org/jahia/modules/appshell/Main.java, src/main/resources/META-INF/urlrewrite-app-shell.xml
https://jira.jahia.org/browse/QA-13736
=> QA-13736: Added file hash

.circleci/.circleci.settings.xml, .circleci/config.yml
This is to align with a change done recently by @bpapez
=> Updated config to include the latest update to the sonar job in Jahia Orb

yarn.lock
https://jira.jahia.org/browse/DMF-4887
=> DMF-4887 : upgrade moonstone version

yarn.lock
https://jira.jahia.org/browse/BACKLOG-16359
Moonstone upgrade
=> BACKLOG-16359 Upgrade moonstone in for yarn.lock

src/javascript/apollo/client.js
https://jira.jahia.org/browse/BACKLOG-16381
=> BACKLOG-16381: Changed websocket endpoint

.circleci/config.yml
https://jira.jahia.org/browse/BACKLOG-15992
=> BACKLOG-15992 - Use latest version of Jahia orb

.circleci/config.yml, pom.xml
=> Updated to latest version of the orb and module signature

LICENSE, pom.xml, src/main/java/org/jahia/modules/appshell/License.java, src/main/java/org/jahia/modules/appshell/Main.java
https://jira.jahia.org/browse/QA-14203
=> QA-14203 - Update copyright year and java header

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-16962
=> BACKLOG-16962: Fix cache

src/javascript/apollo/client.js
https://jira.jahia.org/browse/QA-14253
=> QA-14253: Define regex outside of loop for perf improvement

package.json, src/javascript/apollo/client.js, yarn.lock
https://jira.jahia.org/browse/TECH-320
The current graphql-java-servlet does not seem to support graphql-ws protocol, fallback to previous subscriptions-transport-ws
=> TECH-320: restore subscriptions-transport-ws link

pom.xml
https://jira.jahia.org/browse/BACKLOG-16899
=> BACKLOG-16899: Revert 2.6.0 release

.eslintrc.json
https://jira.jahia.org/browse/BACKLOG-16899
Failure from release here https://app.circleci.com/pipelines/github/Jahia/JahiaReleaseTool/1283/workflows/d4275bb6-47f7-4c75-8e7a-938b6d818d48/jobs/2519
```] [ERROR] Oops! Something went wrong! :(
[INFO] [ERROR] 
[INFO] [ERROR] ESLint: 7.32.0
[INFO] [ERROR] 
[INFO] [ERROR] ESLint couldn't determine the plugin "jest" uniquely.
[INFO] [ERROR] 
[INFO] [ERROR] - /home/circleci/automated_jahia_releases/jahia-build-dir/app-shell/target/checkout/node_modules/eslint-plugin-jest/lib/index.js (loaded in ".eslintrc.json » @jahia/eslint-config")
[INFO] [ERROR] - /home/circleci/automated_jahia_releases/jahia-build-dir/app-shell/node_modules/eslint-plugin-jest/lib/index.js (loaded in "../../.eslintrc.json » @jahia/eslint-config")
[INFO] [ERROR] 
[INFO] …
```
=> BACKLOG-16899: Fix eslint issue on release:perform

pom.xml
=> Updated signature following release

docs/declare-new-module.md, src/main/java/org/jahia/modules/appshell/AppInfo.java, src/main/java/org/jahia/modules/appshell/Main.java
- Add new support for Javascript applications to declare URL patterns that will be used to parse incoming URLs to detect the current site.
- Add site detection by hostname as well
- Add documentation on how to use and declare the new URL patterns
=> QA-14102 Fix site user login

.github/workflows/manual-run.yml, .github/workflows/nightly.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml
https://jira.jahia.org/browse/TECH-1081
Update deprecated steps
=> TECH-1081 Update deprecated steps

src/main/resources/root.jsp
This reverts commit 02bcd10ec77062ad0e56020b3e29cad6225183e0.
=> Revert "Use standards mode"

src/main/java/org/jahia/modules/appshell/Main.java
https://jira.jahia.org/browse/BACKLOG-20461
=> BACKLOG-20461 : fix version support for redirecting to custom error page

src/main/java/org/jahia/modules/appshell/Main.java
https://jira.jahia.org/browse/BACKLOG-20461
=> BACKLOG-20461 : fix version test

.github/maven.settings.xml
https://jira.jahia.org/browse/BACKLOG-20830
=> BACKLOG-20830 - Add missing staging repo credentials

.github/workflows/nightly.yml
=> TECH-1415: Fixed nightly workflow

src/main/java/org/jahia/modules/appshell/Main.java, src/main/resources/root.jsp
https://jira.jahia.org/browse/QA-15003
=> QA-15003 : ensure site is revolved correctly

.github/workflows/manual-run.yml, .github/workflows/nightly.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, .github/workflows/schedule-sonar.yml, pom.xml
https://jira.jahia.org/browse/TECH-1639
=> TECH-1639: Updated GitHub Actions versions

.github/workflows/on-code-change.yml, package.json, yarn.lock
https://jira.jahia.org/browse/SEC-104
=> SEC-104: Update data-helper to 1.0.12

pom.xml
https://jira.jahia.org/browse/BACKLOG-23192
=> BACKLOG-23192: Bump parent version to 8.1.3.0

pom.xml
https://jira.jahia.org/browse/BACKLOG-23183
=> BACKLOG-23183: Bump parent version to 8.1.3.0

package.json, webpack.shared.js, yarn.lock
https://jira.jahia.org/browse/QA-15281
=> QA-15281 : upgrade design-system-kit 

.github/workflows/on-release.yml
https://jira.jahia.org/browse/BACKLOG-23192
=> BACKLOG-23192: Add missing param for the Slack notification

src/main/resources/root.jsp
https://jira.jahia.org/browse/BACKLOG-22920
=> BACKLOG-22920 : fix js console error (jahia loader) + use moonstone styles for loader

src/main/resources/root.jsp
https://jira.jahia.org/browse/QA-15178
=> QA-15178: fix encoding issue in profile name in main menu
